[[news]]
date = "2026-07"
content = "Our work on scene text image super-resolution was accepted by ACM Multimedia 2026 🎉"

[[news]]
date = "2026-05"
content = "Our work on scene text tracking was accepted by ICML 2026 🎉"

[[news]]
date = "2026-05"
content = "Our invention patent for scene text tracking was granted in China"
